### PR TITLE
Updated Esri endpoints

### LINKED ISSUE #15: Review data changes
The DSA team created a pull request to updates some data layers. We need to review the changes to make sure all functionality is working correctly.

### PR DESCRIPTION
**Pull request by karlkaebnick**
## Fixes # 
--------

Some of the current endpoints in use point do not use the latest data.

## Changes proposed
---------
(What are you proposing we change? How does this impact end users? Are manual or automatic updates required?)

- Latest Esri data for certain datasets will be available in the Development Opportunities web app - for more details see https://cidetroitmius.sharepoint.com/:x:/r/sites/M365-DoIT-DSA/Shared%20Documents/DSA%20Clients/HRD%20-%20PDD%20-%20Development%20Opportunities%20App/SHARE%20-%20Development%20Opportunities%20App/Data%20Layers%20-%20Development%20Opportunities%20App.xlsx?d=wb953f237b6ec438ab04ecdfebb6bc257&csf=1&web=1&e=Zy8Llw

### CODE REVIEW

**Comment by alaurenz** [comment]
Hi @jedgar1mx, we hope to make these layer changes live so folks using the App can see the updated layers. Have you reviewed this code?

**Comment by jedgar1mx** [comment]
Looks like there are some issues with the new vector layer. We are getting errors.

{
  "error": {
    "code": 404,
    "message": "Requested Service not available.",
    "details": null
  }
}

**Comment by jmcbroom** [comment]
@jedgar1mx double checked this one -- it is responsive and displaying locally in a separate app so I think we should be good now

**Comment by jedgar1mx** [comment]
Changes looks good.

**Pull request merged**
